apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXB3
  REDIS_PASSWORD: cmVkaXM=
  APIKEY: ZWNiYzM5NmY0Nm1zaGI2NWNiYjFmODJjZjMzNHAxZmNjODdqc25hNWU5NjJhM2M1NDI=
